name: YggdrasilsBark
version: 1.0
main: wbe.yggdrasilsBark.YggdrasilsBark
api-version: 1.21
author: wbe
depend: [MythicMobs, mcMMO, PlaceholderAPI]
commands:
  YggdrasilsBark:
    description: YggdrasilsBark main command
    aliases: [yb, yggdrasilsb, ybark]
    permission: yggdrasilsbark.command
